// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react'

export async function getRoutes() {
  return {
    routes: {
      '1': { path: '/', layout: false, file: '@/pages/index.tsx', id: '1' },
      '2': { path: '/home', title: '首页', file: '@/pages/home/index.tsx', parentId: '1', id: '2' },
      '3': { path: '/', redirect: '/home', parentId: '1', id: '3' },
      '4': { path: '*', redirect: '/404', parentId: '1', id: '4' },
      '5': { path: '/404', layout: false, title: '页面丢失', file: '@/pages/404.tsx', id: '5' },
    },
    routeComponents: {
      '1': React.lazy(() => import(/* webpackChunkName: "p__index" */ '@/pages/index.tsx')),
      '2': React.lazy(
        () => import(/* webpackChunkName: "p__home__index" */ '@/pages/home/index.tsx'),
      ),
      '3': React.lazy(() => import('./EmptyRoute')),
      '4': React.lazy(() => import('./EmptyRoute')),
      '5': React.lazy(() => import(/* webpackChunkName: "p__404" */ '@/pages/404.tsx')),
    },
  }
}
