// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @umijs/renderer-*
export {
  createBrowserHistory,
  createHashHistory,
  createMemoryHistory,
  createSearchParams,
  matchPath,
  matchRoutes,
  Navigate,
  NavLink,
  Outlet,
  resolvePath,
  useLocation,
  useMatch,
  useNavigate,
  useOutlet,
  useOutletContext,
  useParams,
  useResolvedPath,
  useRoutes,
  useSearchParams,
  useAppData,
  useClientLoaderData,
  useServerLoaderData,
  renderClient,
  Link,
  useRouteData,
  __useFetcher,
  withRouter,
} from '/Users/cooky/workroot/ashermed/asm-umi-template/node_modules/.pnpm/@umijs+renderer-react@4.0.8_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export {
  ApplyPluginsType,
  PluginManager,
} from '/Users/cooky/workroot/ashermed/asm-umi-template/node_modules/.pnpm/umi@4.0.8_zy26kbmuysvbdo7dl6kzjas6ri/node_modules/umi/client/client/plugin.js'
export { history, createHistory } from './core/history'
export { terminal } from './core/terminal'
// plugins
export {
  Access,
  useAccess,
  useAccessMarkedRoutes,
} from '/Users/cooky/workroot/ashermed/asm-umi-template/src/.umi-test/plugin-access'
export {
  addLocale,
  setLocale,
  getLocale,
  getIntl,
  useIntl,
  injectIntl,
  formatMessage,
  FormattedMessage,
  getAllLocales,
  SelectLang,
} from '/Users/cooky/workroot/ashermed/asm-umi-template/src/.umi-test/plugin-locale'
export {
  Provider,
  useModel,
} from '/Users/cooky/workroot/ashermed/asm-umi-template/src/.umi-test/plugin-model'
export {
  useRequest,
  UseRequestProvider,
  request,
} from '/Users/cooky/workroot/ashermed/asm-umi-template/src/.umi-test/plugin-request'
// plugins types.d.ts
export * from '/Users/cooky/workroot/ashermed/asm-umi-template/src/.umi-test/plugin-request/types.d'
